services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: hirable.app
  #   ports:
  #     - "3021:3021"
  #   depends_on:
  #     - postgres
  #     - localstack
  #   volumes:
  #     - ./src:/home/node/app/src
  #     - /home/node/app/node_modules

  postgres:
    image: postgres:13
    container_name: hirable.pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hirable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: hirable.localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:7.2.4
    env_file:
      - env/.env.local
    container_name: hirable.cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redispw
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hirable-pgadmin
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:
  redis_data:
  localstack_data:
    driver: local
